
import type { BibleBook } from './types';

// This file is generated from bible-characters to provide a quick lookup
// for parsing verse references without needing to have all books in memory.
// It can be expanded as needed.

interface BookAbbrevMap {
  [key: string]: BibleBook;
}

export const bibleBooksByAbbrev: BookAbbrevMap = {
  gn: {
    id: 'genesis',
    abbrev: { pt: 'gn', en: 'gn' },
    author: 'Moisés',
    chapters: 50,
    group: 'Pentateuco',
    name: 'Gênesis',
    testament: 'VT',
  },
  ex: {
    id: 'exodo',
    abbrev: { pt: 'ex', en: 'ex' },
    author: 'Moisés',
    chapters: 40,
    group: 'Pentateuco',
    name: 'Êxodo',
    testament: 'VT',
  },
  lv: {
    id: 'levitico',
    abbrev: { pt: 'lv', en: 'lv' },
    author: 'Moisés',
    chapters: 27,
    group: 'Pentateuco',
    name: 'Levítico',
    testament: 'VT',
  },
  nm: {
    id: 'numeros',
    abbrev: { pt: 'nm', en: 'num' },
    author: 'Moisés',
    chapters: 36,
    group: 'Pentateuco',
    name: 'Números',
    testament: 'VT',
  },
  dt: {
    id: 'deuteronomio',
    abbrev: { pt: 'dt', en: 'dt' },
    author: 'Moisés',
    chapters: 34,
    group: 'Pentateuco',
    name: 'Deuteronômio',
    testament: 'VT',
  },
  js: {
    id: 'josue',
    abbrev: { pt: 'js', en: 'jsh' },
    author: 'Josué',
    chapters: 24,
    group: 'Históricos',
    name: 'Josué',
    testament: 'VT',
  },
  jz: {
    id: 'juizes',
    abbrev: { pt: 'jz', en: 'jud' },
    author: 'Samuel',
    chapters: 21,
    group: 'Históricos',
    name: 'Juízes',
    testament: 'VT',
  },
  rt: {
    id: 'rute',
    abbrev: { pt: 'rt', en: 'rt' },
    author: 'Samuel',
    chapters: 4,
    group: 'Históricos',
    name: 'Rute',
    testament: 'VT',
  },
  '1sm': {
    id: '1samuel',
    abbrev: { pt: '1sm', en: '1sm' },
    author: 'Samuel, Gade e Natã',
    chapters: 31,
    group: 'Históricos',
    name: '1º Samuel',
    testament: 'VT',
  },
  '2sm': {
    id: '2samuel',
    abbrev: { pt: '2sm', en: '2sm' },
    author: 'Samuel, Gade e Natã',
    chapters: 24,
    group: 'Históricos',
    name: '2º Samuel',
    testament: 'VT',
  },
  '1rs': {
    id: '1reis',
    abbrev: { pt: '1rs', en: '1ki' },
    author: 'Jeremias',
    chapters: 22,
    group: 'Históricos',
    name: '1º Reis',
    testament: 'VT',
  },
  '2rs': {
    id: '2reis',
    abbrev: { pt: '2rs', en: '2ki' },
    author: 'Jeremias',
    chapters: 25,
    group: 'Históricos',
    name: '2º Reis',
    testament: 'VT',
  },
  '1cr': {
    id: '1cronicas',
    abbrev: { pt: '1cr', en: '1ch' },
    author: 'Esdras',
    chapters: 29,
    group: 'Históricos',
    name: '1º Crônicas',
    testament: 'VT',
  },
  '2cr': {
    id: '2cronicas',
    abbrev: { pt: '2cr', en: '2ch' },
    author: 'Esdras',
    chapters: 36,
    group: 'Históricos',
    name: '2º Crônicas',
    testament: 'VT',
  },
  ed: {
    id: 'esdras',
    abbrev: { pt: 'ed', en: 'ezr' },
    author: 'Esdras',
    chapters: 10,
    group: 'Históricos',
    name: 'Esdras',
    testament: 'VT',
  },
  ne: {
    id: 'neemias',
    abbrev: { pt: 'ne', en: 'ne' },
    author: 'Neemias',
    chapters: 13,
    group: 'Históricos',
    name: 'Neemias',
    testament: 'VT',
  },
  et: {
    id: 'ester',
    abbrev: { pt: 'et', en: 'et' },
    author: 'Desconhecido',
    chapters: 10,
    group: 'Históricos',
    name: 'Ester',
    testament: 'VT',
  },
  job: {
    id: 'jo',
    abbrev: { pt: 'job', en: 'job' },
    author: 'Desconhecido',
    chapters: 42,
    group: 'Poéticos',
    name: 'Jó',
    testament: 'VT',
  },
  sl: {
    id: 'salmos',
    abbrev: { pt: 'sl', en: 'ps' },
    author: 'Davi, Asafe, os filhos de Corá, Salomão, Hemã, Etã e Moisés',
    chapters: 150,
    group: 'Poéticos',
    name: 'Salmos',
    testament: 'VT',
  },
  pv: {
    id: 'proverbios',
    abbrev: { pt: 'pv', en: 'prv' },
    author: 'Salomão',
    chapters: 31,
    group: 'Poéticos',
    name: 'Provérbios',
    testament: 'VT',
  },
  ec: {
    id: 'eclesiastes',
    abbrev: { pt: 'ec', en: 'ec' },
    author: 'Salomão',
    chapters: 12,
    group: 'Poéticos',
    name: 'Eclesiastes',
    testament: 'VT',
  },
  ct: {
    id: 'cantares',
    abbrev: { pt: 'ct', en: 'so' },
    author: 'Salomão',
    chapters: 8,
    group: 'Poéticos',
    name: 'Cantares',
    testament: 'VT',
  },
  is: {
    id: 'isaias',
    abbrev: { pt: 'is', en: 'is' },
    author: 'Isaías',
    chapters: 66,
    group: 'Profetas Maiores',
    name: 'Isaías',
    testament: 'VT',
  },
  jr: {
    id: 'jeremias',
    abbrev: { pt: 'jr', en: 'jer' },
    author: 'Jeremias',
    chapters: 52,
    group: 'Profetas Maiores',
    name: 'Jeremias',
    testament: 'VT',
  },
  lm: {
    id: 'lamentacoes',
    abbrev: { pt: 'lm', en: 'lm' },
    author: 'Jeremias',
    chapters: 5,
    group: 'Profetas Maiores',
    name: 'Lamentações',
    testament: 'VT',
  },
  ez: {
    id: 'ezequiel',
    abbrev: { pt: 'ez', en: 'ez' },
    author: 'Ezequiel',
    chapters: 48,
    group: 'Profetas Maiores',
    name: 'Ezequiel',
    testament: 'VT',
  },
  dn: {
    id: 'daniel',
    abbrev: { pt: 'dn', en: 'dn' },
    author: 'Daniel',
    chapters: 12,
    group: 'Profetas Maiores',
    name: 'Daniel',
    testament: 'VT',
  },
  os: {
    id: 'oseias',
    abbrev: { pt: 'os', en: 'ho' },
    author: 'Oséias',
    chapters: 14,
    group: 'Profetas Menores',
    name: 'Oséias',
    testament: 'VT',
  },
  jl: {
    id: 'joel',
    abbrev: { pt: 'jl', en: 'jl' },
    author: 'Joel',
    chapters: 3,
    group: 'Profetas Menores',
    name: 'Joel',
    testament: 'VT',
  },
  am: {
    id: 'amos',
    abbrev: { pt: 'am', en: 'am' },
    author: 'Amós',
    chapters: 9,
    group: 'Profetas Menores',
    name: 'Amós',
    testament: 'VT',
  },
  ob: {
    id: 'obadias',
    abbrev: { pt: 'ob', en: 'ob' },
    author: 'Obadias',
    chapters: 1,
    group: 'Profetas Menores',
    name: 'Obadias',
    testament: 'VT',
  },
  jn: {
    id: 'jonas',
    abbrev: { pt: 'jn', en: 'jn' },
    author: 'Jonas',
    chapters: 4,
    group: 'Profetas Menores',
    name: 'Jonas',
    testament: 'VT',
  },
  mq: {
    id: 'miqueias',
    abbrev: { pt: 'mq', en: 'mi' },
    author: 'Miquéias',
    chapters: 7,
    group: 'Profetas Menores',
    name: 'Miquéias',
    testament: 'VT',
  },
  na: {
    id: 'naum',
    abbrev: { pt: 'na', en: 'na' },
    author: 'Naum',
    chapters: 3,
    group: 'Profetas Menores',
    name: 'Naum',
    testament: 'VT',
  },
  hc: {
    id: 'habacuque',
    abbrev: { pt: 'hc', en: 'hk' },
    author: 'Habacuque',
    chapters: 3,
    group: 'Profetas Menores',
    name: 'Habacuque',
    testament: 'VT',
  },
  sf: {
    id: 'sofonias',
    abbrev: { pt: 'sf', en: 'zp' },
    author: 'Sofonias',
    chapters: 3,
    group: 'Profetas Menores',
    name: 'Sofonias',
    testament: 'VT',
  },
  ag: {
    id: 'ageu',
    abbrev: { pt: 'ag', en: 'hg' },
    author: 'Ageu',
    chapters: 2,
    group: 'Profetas Menores',
    name: 'Ageu',
    testament: 'VT',
  },
  zc: {
    id: 'zacarias',
    abbrev: { pt: 'zc', en: 'zc' },
    author: 'Zacarias',
    chapters: 14,
    group: 'Profetas Menores',
    name: 'Zacarias',
    testament: 'VT',
  },
  ml: {
    id: 'malaquias',
    abbrev: { pt: 'ml', en: 'ml' },
    author: 'Malaquias',
    chapters: 4,
    group: 'Profetas Menores',
    name: 'Malaquias',
    testament: 'VT',
  },
  mt: {
    id: 'mateus',
    abbrev: { pt: 'mt', en: 'mt' },
    author: 'Mateus',
    chapters: 28,
    group: 'Evangelhos',
    name: 'Mateus',
    testament: 'NT',
  },
  mc: {
    id: 'marcos',
    abbrev: { pt: 'mc', en: 'mk' },
    author: 'Marcos',
    chapters: 16,
    group: 'Evangelhos',
    name: 'Marcos',
    testament: 'NT',
  },
  lc: {
    id: 'lucas',
    abbrev: { pt: 'lc', en: 'lk' },
    author: 'Lucas',
    chapters: 24,
    group: 'Evangelhos',
    name: 'Lucas',
    testament: 'NT',
  },
  jo: {
    id: 'joao',
    abbrev: { pt: 'jo', en: 'jn' },
    author: 'João',
    chapters: 21,
    group: 'Evangelhos',
    name: 'João',
    testament: 'NT',
  },
  at: {
    id: 'atos',
    abbrev: { pt: 'at', en: 'act' },
    author: 'Lucas',
    chapters: 28,
    group: 'Histórico',
    name: 'Atos',
    testament: 'NT',
  },
  rm: {
    id: 'romanos',
    abbrev: { pt: 'rm', en: 'rm' },
    author: 'Paulo',
    chapters: 16,
    group: 'Cartas',
    name: 'Romanos',
    testament: 'NT',
  },
  '1co': {
    id: '1corintios',
    abbrev: { pt: '1co', en: '1co' },
    author: 'Paulo',
    chapters: 16,
    group: 'Cartas',
    name: '1ª Coríntios',
    testament: 'NT',
  },
  '2co': {
    id: '2corintios',
    abbrev: { pt: '2co', en: '2co' },
    author: 'Paulo',
    chapters: 13,
    group: 'Cartas',
    name: '2ª Coríntios',
    testament: 'NT',
  },
  gl: {
    id: 'galatas',
    abbrev: { pt: 'gl', en: 'ga' },
    author: 'Paulo',
    chapters: 6,
    group: 'Cartas',
    name: 'Gálatas',
    testament: 'NT',
  },
  ef: {
    id: 'efesios',
    abbrev: { pt: 'ef', en: 'eph' },
    author: 'Paulo',
    chapters: 6,
    group: 'Cartas',
    name: 'Efésios',
    testament: 'NT',
  },
  fp: {
    id: 'filipenses',
    abbrev: { pt: 'fp', en: 'ph' },
    author: 'Paulo',
    chapters: 4,
    group: 'Cartas',
    name: 'Filipenses',
    testament: 'NT',
  },
  cl: {
    id: 'colossenses',
    abbrev: { pt: 'cl', en: 'co' },
    author: 'Paulo',
    chapters: 4,
    group: 'Cartas',
    name: 'Colossenses',
    testament: 'NT',
  },
  '1ts': {
    id: '1tessalonicenses',
    abbrev: { pt: '1ts', en: '1th' },
    author: 'Paulo',
    chapters: 5,
    group: 'Cartas',
    name: '1ª Tessalonicenses',
    testament: 'NT',
  },
  '2ts': {
    id: '2tessalonicenses',
    abbrev: { pt: '2ts', en: '2th' },
    author: 'Paulo',
    chapters: 3,
    group: 'Cartas',
    name: '2ª Tessalonicenses',
    testament: 'NT',
  },
  '1tm': {
    id: '1timoteo',
    abbrev: { pt: '1tm', en: '1tm' },
    author: 'Paulo',
    chapters: 6,
    group: 'Cartas',
    name: '1ª Timóteo',
    testament: 'NT',
  },
  '2tm': {
    id: '2timoteo',
    abbrev: { pt: '2tm', en: '2tm' },
    author: 'Paulo',
    chapters: 4,
    group: 'Cartas',
    name: '2ª Timóteo',
    testament: 'NT',
  },
  tt: {
    id: 'tito',
    abbrev: { pt: 'tt', en: 'tt' },
    author: 'Paulo',
    chapters: 3,
    group: 'Cartas',
    name: 'Tito',
    testament: 'NT',
  },
  fm: {
    id: 'filemom',
    abbrev: { pt: 'fm', en: 'phm' },
    author: 'Paulo',
    chapters: 1,
    group: 'Cartas',
    name: 'Filemom',
    testament: 'NT',
  },
  hb: {
    id: 'hebreus',
    abbrev: { pt: 'hb', en: 'hb' },
    author: 'Desconhecido',
    chapters: 13,
    group: 'Cartas',
    name: 'Hebreus',
    testament: 'NT',
  },
  tg: {
    id: 'tiago',
    abbrev: { pt: 'tg', en: 'jm' },
    author: 'Tiago',
    chapters: 5,
    group: 'Cartas',
    name: 'Tiago',
    testament: 'NT',
  },
  '1pe': {
    id: '1pedro',
    abbrev: { pt: '1pe', en: '1pe' },
    author: 'Pedro',
    chapters: 5,
    group: 'Cartas',
    name: '1ª Pedro',
    testament: 'NT',
  },
  '2pe': {
    id: '2pedro',
    abbrev: { pt: '2pe', en: '2pe' },
    author: 'Pedro',
    chapters: 3,
    group: 'Cartas',
    name: '2ª Pedro',
    testament: 'NT',
  },
  '1jo': {
    id: '1joao',
    abbrev: { pt: '1jo', en: '1jn' },
    author: 'João',
    chapters: 5,
    group: 'Cartas',
    name: '1ª João',
    testament: 'NT',
  },
  '2jo': {
    id: '2joao',
    abbrev: { pt: '2jo', en: '2jn' },
    author: 'João',
    chapters: 1,
    group: 'Cartas',
    name: '2ª João',
    testament: 'NT',
  },
  '3jo': {
    id: '3joao',
    abbrev: { pt: '3jo', en: '3jn' },
    author: 'João',
    chapters: 1,
    group: 'Cartas',
    name: '3ª João',
    testament: 'NT',
  },
  jd: {
    id: 'judas',
    abbrev: { pt: 'jd', en: 'jd' },
    author: 'Judas',
    chapters: 1,
    group: 'Cartas',
    name: 'Judas',
    testament: 'NT',
  },
  ap: {
    id: 'apocalipse',
    abbrev: { pt: 'ap', en: 're' },
    author: 'João',
    chapters: 22,
    group: 'Revelações',
    name: 'Apocalipse',
    testament: 'NT',
  },
};
