
import type { BibleBook } from './types';

// This file is generated from bible-characters to provide a quick lookup
// for parsing verse references without needing to have all books in memory.
// It can be expanded as needed.

interface BookAbbrevMap {
  [key: string]: BibleBook;
}

export const bibleBooksByAbbrev: BookAbbrevMap = {
  gn: {
    id: 'genesis',
    abbrev: { pt: 'gn', en: 'gn' },
    author: 'Moisés',
    chapters: 50,
    group: 'Pentateuco',
    name: 'Gênesis',
    testament: 'VT',
  },
  ex: {
    id: 'exodo',
    abbrev: { pt: 'ex', en: 'ex' },
    author: 'Moisés',
    chapters: 40,
    group: 'Pentateuco',
    name: 'Êxodo',
    testament: 'VT',
  },
  nm: {
    id: 'numeros',
    abbrev: { pt: 'nm', en: 'num' },
    author: 'Moisés',
    chapters: 36,
    group: 'Pentateuco',
    name: 'Números',
    testament: 'VT',
  },
  dt: {
    id: 'deuteronomio',
    abbrev: { pt: 'dt', en: 'dt' },
    author: 'Moisés',
    chapters: 34,
    group: 'Pentateuco',
    name: 'Deuteronômio',
    testament: 'VT',
  },
  '1sm': {
    id: '1samuel',
    abbrev: { pt: '1sm', en: '1sm' },
    author: 'Samuel, Gade e Natã',
    chapters: 31,
    group: 'Históricos',
    name: '1º Samuel',
    testament: 'VT',
  },
  '2sm': {
    id: '2samuel',
    abbrev: { pt: '2sm', en: '2sm' },
    author: 'Samuel, Gade e Natã',
    chapters: 24,
    group: 'Históricos',
    name: '2º Samuel',
    testament: 'VT',
  },
  '1cr': {
    id: '1cronicas',
    abbrev: { pt: '1cr', en: '1ch' },
    author: 'Esdras',
    chapters: 29,
    group: 'Históricos',
    name: '1º Crônicas',
    testament: 'VT',
  },
  ne: {
    id: 'neemias',
    abbrev: { pt: 'ne', en: 'ne' },
    author: 'Neemias',
    chapters: 13,
    group: 'Históricos',
    name: 'Neemias',
    testament: 'VT',
  },
  et: {
    id: 'ester',
    abbrev: { pt: 'et', en: 'et' },
    author: 'Desconhecido',
    chapters: 10,
    group: 'Históricos',
    name: 'Ester',
    testament: 'VT',
  },
  sl: {
    id: 'salmos',
    abbrev: { pt: 'sl', en: 'ps' },
    author: 'Davi, Asafe, os filhos de Corá, Salomão, Hemã, Etã e Moisés',
    chapters: 150,
    group: 'Poéticos',
    name: 'Salmos',
    testament: 'VT',
  },
  pv: {
    id: 'proverbios',
    abbrev: { pt: 'pv', en: 'prv' },
    author: 'Salomão',
    chapters: 31,
    group: 'Poéticos',
    name: 'Provérbios',
    testament: 'VT',
  },
  ec: {
    id: 'eclesiastes',
    abbrev: { pt: 'ec', en: 'ec' },
    author: 'Salomão',
    chapters: 12,
    group: 'Poéticos',
    name: 'Eclesiastes',
    testament: 'VT',
  },
  mt: {
    id: 'mateus',
    abbrev: { pt: 'mt', en: 'mt' },
    author: 'Mateus',
    chapters: 28,
    group: 'Evangelhos',
    name: 'Mateus',
    testament: 'NT',
  },
  lc: {
    id: 'lucas',
    abbrev: { pt: 'lc', en: 'lk' },
    author: 'Lucas',
    chapters: 24,
    group: 'Evangelhos',
    name: 'Lucas',
    testament: 'NT',
  },
  jo: {
    id: 'joao',
    abbrev: { pt: 'jo', en: 'jn' },
    author: 'João',
    chapters: 21,
    group: 'Evangelhos',
    name: 'João',
    testament: 'NT',
  },
  at: {
    id: 'atos',
    abbrev: { pt: 'at', en: 'act' },
    author: 'Lucas',
    chapters: 28,
    group: 'Histórico',
    name: 'Atos',
    testament: 'NT',
  },
  rm: {
    id: 'romanos',
    abbrev: { pt: 'rm', en: 'rm' },
    author: 'Paulo',
    chapters: 16,
    group: 'Cartas',
    name: 'Romanos',
    testament: 'NT',
  },
  gl: {
    id: 'galatas',
    abbrev: { pt: 'gl', en: 'ga' },
    author: 'Paulo',
    chapters: 6,
    group: 'Cartas',
    name: 'Gálatas',
    testament: 'NT',
  },
  ef: {
    id: 'efesios',
    abbrev: { pt: 'ef', en: 'eph' },
    author: 'Paulo',
    chapters: 6,
    group: 'Cartas',
    name: 'Efésios',
    testament: 'NT',
  },
  fp: {
    id: 'filipenses',
    abbrev: { pt: 'fp', en: 'ph' },
    author: 'Paulo',
    chapters: 4,
    group: 'Cartas',
    name: 'Filipenses',
    testament: 'NT',
  },
  cl: {
    id: 'colossenses',
    abbrev: { pt: 'cl', en: 'co' },
    author: 'Paulo',
    chapters: 4,
    group: 'Cartas',
    name: 'Colossenses',
    testament: 'NT',
  },
  '2tm': {
    id: '2timoteo',
    abbrev: { pt: '2tm', en: '2tm' },
    author: 'Paulo',
    chapters: 4,
    group: 'Cartas',
    name: '2ª Timóteo',
    testament: 'NT',
  },
  hb: {
    id: 'hebreus',
    abbrev: { pt: 'hb', en: 'hb' },
    author: 'Desconhecido',
    chapters: 13,
    group: 'Cartas',
    name: 'Hebreus',
    testament: 'NT',
  },
  '1pe': {
    id: '1pedro',
    abbrev: { pt: '1pe', en: '1pe' },
    author: 'Pedro',
    chapters: 5,
    group: 'Cartas',
    name: '1ª Pedro',
    testament: 'NT',
  },
};
